
apiVersion: v1
kind: Service
metadata:
  name: loki-headless
spec:
  clusterIP: None
  ports:
    - port: 3100
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics    
---
apiVersion: v1
kind: Service
metadata:
  name: loki-memberlist
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 7946
      targetPort: memberlist-port
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  type: ClusterIP
  ports:
    - port: 3100
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics     