apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml

commonLabels:
  app: rolldice

images:
  - name: ghcr.io/luizpra/app-non-instrumented-rolldice
    newName: ghcr.io/luizpra/app-non-instrumented-rolldice
    newTag: 0.0.2

replicas:
  - name: rolldice
    count: 1