apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  type: ClusterIP
  ports:
    - port: 5601
      protocol: TCP
      name: http
      targetPort: 5601
    # Ranchar compability
    - port: 80
      protocol: TCP
      name: http
      targetPort: 5601  
