apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiali
spec:
  template:
    metadata:
      labels:
    spec:
      serviceAccountName: kiali
      containers:
        - name: kiali
          image: "quay.io/kiali/kiali:v1.55"
          imagePullPolicy: "Always"
          command:
            - "/opt/kiali/kiali"
            - "-config"
            - "/kiali-configuration/config.yaml"               
          ports:
            - name: api-port
              containerPort: 20001
            - name: http-metrics
              containerPort: 9090
          env:
          - name: ACTIVE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace              
          envFrom:
            - configMapRef:
                name: kiali-envs
          readinessProbe:
            httpGet:
              path: /kiali/healthz
              port: api-port
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /kiali/healthz
              port: api-port
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
            requests:
              cpu: 10m
              memory: 64Mi
          volumeMounts:
            - name: config-volume
              mountPath: "/kiali-configuration"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      volumes:
        - name: config-volume
          configMap:
            name: kiali

