namespace: istio-system

resources:
  - serviceaccount.yaml
  - service.yaml
  - deployment.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml

commonLabels:
  app: kiali

images:
  - name: quay.io/kiali/kiali
    newName: quay.io/kiali/kiali
    newTag: v1.55

replicas:
  - name: kiali
    count: 1

configMapGenerator:
  - name: kiali-envs
    envs:
      - kiali.env
  - name: kiali
    files:
      - config.yaml
