# -*- mode: ruby -*-
# vi: set ft=ruby :

# ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false

  # config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Node
  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/jammy64"
    master.vm.box_check_update = false
    master.vm.hostname = "kubernetes-master"
    master.vm.network "private_network", ip: "192.168.56.100"
  
    master.vm.provider "virtualbox" do |v|
      v.name = "master"
      v.memory = 2048
      v.cpus = 2
    end
    # server.vm.provision "shell", path: "init.sh"
  end

  # Kubernetes Worker Nodes
  NodeCount = 3
  (1..NodeCount).each do |i|

    config.vm.define "kubernetes-node#{i}" do |node|
      node.vm.box = "ubuntu/jammy64"
      node.vm.box_check_update = false
      #node.vm.box_version = "v20210112.0.0"
      node.vm.hostname = "kubernetes-node#{i}"
      node.vm.network "private_network", ip: "192.168.56.10#{i}"

      node.vm.provider "virtualbox" do |v|
        v.name = "node#{i}"
        v.memory = 2048
        v.cpus = 2
      end
      # node.vm.provision "shell", path: "init.sh"
    end
  end
end