resources:
- https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/high-availability-1.21+.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kubelet-insecure-tls
    target: 
      kind: Deployment 
      name: metrics-server
