apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolldice
spec:
  template:
    metadata:
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-python: "non-otel-python-instrumentation"
    spec:
      containers:
      - name: rolldice
        image: ghcr.io/luizpra/app-non-instrumented-rolldice:0.0.2
        imagePullPolicy: Always        
        ports:
          - containerPort: 5000
            protocol: TCP