# -*- mode: ruby -*-
# vi: set ft=ruby :

# ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.define "kube-api" do |lb|
    lb.vm.box = "ubuntu/jammy64"
    lb.vm.box_check_update = false
    lb.vm.hostname = "kube-api"
    lb.vm.network "private_network", ip: "192.168.56.10"
    lb.vm.provider "virtualbox" do |v|
      v.name = "kube-api"
      v.memory = 1024
      v.cpus = 1
    end
    lb.vm.provision "shell", privileged: true, path: "nginx-install.sh"
  end

  MasterCount = 3
  (1..MasterCount).each do |i|
    config.vm.define "master#{i}" do |master|
      master.vm.box = "ubuntu/jammy64"
      master.vm.box_check_update = false
      master.vm.hostname = "master#{i}"
      master.vm.network "private_network", ip: "192.168.56.1#{i}"
      master.vm.provider "virtualbox" do |v|
        v.name = "master#{i}"
        v.memory = 2048
        v.cpus = 2
      end
      master.vm.provision "shell" do |s|
        s.privileged = true
        s.path = "install.sh"
        s.env = { 'IS_MASTER' => "true",
                  'IP_ADDRESS' => "192.168.56.1#{i}",
                  'CERT_KEY' => "e6a2eb8581237ab72a4f494f30285ec12a9694d750b9785706a83bfcbbbd2204",
                  'TOKEN' => 'czungj.clmo71x9u7wmeo61',
                  'TOKEN_CA_CERT_HASH' => 'sha256:77848a1451487cf9fc1e44f5f971bbf27f76790a9227596353cc7bfb9c5e5d7d' }
      end
    end
  end

  NodeCount = 3
  (1..NodeCount).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "ubuntu/jammy64"
      node.vm.box_check_update = false
      node.vm.hostname = "node#{i}"
      node.vm.network "private_network", ip: "192.168.56.2#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "node#{i}"
        v.memory = 16384
        v.cpus = 4
      end
      node.vm.provision "shell" do |s|
        s.privileged = true
        s.path = "install.sh"
      end
    end
  end
end
