apiVersion: v1
kind: Service
metadata:
  name: promtail
spec:
  type: "ClusterIP"
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: http-metrics
      port: 3101
      protocol: TCP
      targetPort: 3101      
      